version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mikci
      MYSQL_ROOT_PASSWORD: mikci123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8181:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mikci123
  app:
    build: .
    ports:
      - '5501:80'
    depends_on:
      - db
    links:
      - db
      - phpmyadmin
    volumes:
      - .:/var/www/html
