version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mikci
      MYSQL_USER: root
      MYSQL_PASSWORD: mikci123
      MYSQL_ROOT_PASSWORD: mikci123
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mikci123

  app:
    build: .
    restart: always
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: mikci
      DB_USER: root
      DB_PASSWORD: mikci123

volumes:
  db_data:
